export const SUBSCRIPTIONS_LIST_REQUEST = "SUBSCRIPTIONS_LIST_REQUEST";
export const SUBSCRIPTIONS_LIST_SUCCESS = "SUBSCRIPTIONS_LIST_SUCCESS";
export const SUBSCRIPTIONS_LIST_ERROR = "SUBSCRIPTIONS_LIST_ERROR";

export const SUBSCRIPTIONS_UNSUBSCRIBE_REQUEST = "SUBSCRIPTIONS_UNSUBSCRIBE_REQUEST";
export const SUBSCRIPTIONS_UNSUBSCRIBE_SUCCESS = "SUBSCRIPTIONS_UNSUBSCRIBE_SUCCESS";
export const SUBSCRIPTIONS_UNSUBSCRIBE_ERROR = "SUBSCRIPTIONS_UNSUBSCRIBE_ERROR";

export const INVITATIONS_LIST_REQUEST = "INVITATIONS_LIST_REQUEST";
export const INVITATIONS_LIST_SUCCESS = "INVITATIONS_LIST_SUCCESS";
export const INVITATIONS_LIST_ERROR = "INVITATIONS_LIST_ERROR";

export const INVITATIONS_ACCEPT_REQUEST = "INVITATIONS_ACCEPT_REQUEST";
export const INVITATIONS_ACCEPT_SUCCESS = "INVITATIONS_ACCEPT_SUCCESS";
export const INVITATIONS_ACCEPT_ERROR = "INVITATIONS_ACCEPT_ERROR";