export const ACTIVECOMMUNITIES_LIST_REQUEST = "ACTIVECOMMUNITIES_LIST_REQUEST";
export const ACTIVECOMMUNITIES_LIST_SUCCESS = "ACTIVECOMMUNITIES_LIST_SUCCESS";
export const ACTIVECOMMUNITIES_LIST_ERROR = "ACTIVECOMMUNITIES_LIST_ERROR";

export const ARCHIVECOMMUNITIES_LIST_REQUEST = "ARCHIVECOMMUNITIES_LIST_REQUEST";
export const ARCHIVECOMMUNITIES_LIST_SUCCESS = "ARCHIVECOMMUNITIES_LIST_SUCCESS";
export const ARCHIVECOMMUNITIES_LIST_ERROR = "ARCHIVECOMMUNITIES_LIST_ERROR";